### ISSUE TITLE
.scrollProgress() not working

### ISSUE THREAD

**Issue by heokhe** [arguiot/NoobScroll#1]
Hi
I wanted to use `scrollProgress()` method to create a progress bar, that filles by the page's scrolled percentage.
So, i used: 
`$(window).scrollProgress($('body'), function(e){
      $('#progress').css('width', e + '%')
})`
but it returns me negative value
What to do now?

**Comment by arguiot** [comment]
Download the latest build of NoobScroll, and try this (I changed the docs):
```javascript
$(document).scrollProgress($(window), function (percentage) {
   console.log(percentage + "%"); // for example: 23.53234%
});
```
Thanks for submitting 😊.

By the way, NoobScroll is no longer my main project, you should check out [DisplayJS](https://display.js.org) for more JavaScript cool 😎 stuff.
